spring.application.name=mcp-server
server.port=9092

management.endpoints.web.exposure.include=health,info,metrics,loggers
management.endpoint.health.show-details=always

logging.level.root=INFO
logging.level.com.rbs.customer.mcp.server=INFO

mcp.connectors.jira.enabled=${MCP_JIRA_ENABLED:false}
mcp.connectors.jira.base-url=${MCP_JIRA_BASE_URL:https://your-domain.atlassian.net}
mcp.connectors.jira.cloud-id=${MCP_JIRA_CLOUD_ID:}
mcp.connectors.jira.email=${MCP_JIRA_EMAIL:your-email@company.com}
mcp.connectors.jira.api-token=${MCP_JIRA_API_TOKEN:}
mcp.connectors.jira.project-key=${MCP_JIRA_PROJECT_KEY:OBS}
mcp.connectors.jira.create-issue-path=${MCP_JIRA_CREATE_ISSUE_PATH:/rest/api/3/issue}
mcp.connectors.jira.get-issue-path=${MCP_JIRA_GET_ISSUE_PATH:/rest/api/3/issue}

mcp.connectors.git.enabled=false
mcp.connectors.git.provider=${MCP_GIT_PROVIDER:github}
mcp.connectors.git.repo=${MCP_GIT_REPO:org/repo}
mcp.connectors.git.api-token=${MCP_GIT_API_TOKEN:}

mcp.connectors.cloudwatch.enabled=false
mcp.connectors.cloudwatch.region=${MCP_CLOUDWATCH_REGION:ap-south-1}
mcp.connectors.cloudwatch.log-group=${MCP_CLOUDWATCH_LOG_GROUP:/aws/app/onboarding-service}
mcp.connectors.cloudwatch.lookback-minutes=${MCP_CLOUDWATCH_LOOKBACK_MINUTES:120}
mcp.connectors.cloudwatch.limit=${MCP_CLOUDWATCH_LIMIT:100}


mcp.connectors.s3.enabled=false
mcp.connectors.s3.region=${MCP_S3_REGION:ap-south-1}
mcp.connectors.s3.bucket=${MCP_S3_BUCKET:onboarding-observability-artifacts}
mcp.connectors.s3.prefix=${MCP_S3_PREFIX:incidents/}

mcp.connectors.figma.enabled=false
mcp.connectors.figma.api-token=${MCP_FIGMA_API_TOKEN:}
mcp.connectors.figma.file-key=${MCP_FIGMA_FILE_KEY:}
mcp.connectors.figma.project-name=${MCP_FIGMA_PROJECT_NAME:Customer-Onboarding}

mcp.connectors.database.enabled=false
mcp.connectors.database.jdbc-url=${MCP_DB_JDBC_URL:jdbc:postgresql://localhost:5432/onboarding}
mcp.connectors.database.username=${MCP_DB_USERNAME:onboarding_user}
mcp.connectors.database.password=${MCP_DB_PASSWORD:}

mcp.llm.enabled=${MCP_LLM_ENABLED:false}
mcp.llm.provider=${MCP_LLM_PROVIDER:openai}
mcp.llm.api-key=${MCP_LLM_API_KEY:}
mcp.llm.base-url=${MCP_LLM_BASE_URL:http://localhost:11434/v1}
mcp.llm.model=${MCP_LLM_MODEL:tinyllama}
