apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: onboarding

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - onboarding-service-deployment.yaml
  - onboarding-service-service.yaml
  - mcp-server-deployment.yaml
  - mcp-server-service.yaml

images:
  - name: onboarding-service
    newName: onboarding-service
    newTag: local
  - name: mcp-server
    newName: mcp-server
    newTag: local

